### ISSUE TITLE
JobService, QueueService 리팩터링

### ISSUE THREAD

**Issue by elyo9381** [f-lab-edu/inqueue#32]
### 기존 구조

![기존](https://user-images.githubusercontent.com/33423123/235619080-b475d6e9-aab6-4a57-bcb7-eb9e929d599d.png)

> UserRedisRepsitory : 대기열/작업열에 들어간 인원을 위한 자료구조
> UserRedisTemplate : 큐에 들어간 인원을 위한 Strings, Set 자료 구조 Template
> &nbsp; &nbsp; &nbsp; String 자료 구조 : 유저의 TTL 설정 및 현재 큐에 있는지 확인 용도
> &nbsp; &nbsp; &nbsp; Set 자료 구조 : 큐에 들어간 인원의 사이즈 측정 용도

> WaitQueueRepository : 대기열을 위한 저장소
> WaitQueueRedisTemplate: 대기열을 위한 SortedSet 자료 구조 Template, 큐에 들어간 인원의 사이즈 측정 및 랭킹 측정 용도

- QueueService 대기열/작업열 진입 및 대기열 유저 확인의 모든 역할을 담당하므로 역할을 분산할 필요가 있었다.
- 대기열의 경우 UserRedisRepsitory의 Set자료구조의 역할을 SortedSet이 모두 할 수 있으나, 중복 자료구조인 Set이 생긴다.
    - 스케쥴러를 통한 삭제시, 이중으로 삭제가 되어야 하기 때문에 성능 상 문제가 생긴다.
    - 대기열/작업열 분기 처리를 할 시 코드의 복잡도가 높아질것으로 예상

### 변경된 구조

![변경](https://user-images.githubusercontent.com/33423123/235628533-0fa19fdb-7a36-4aa3-958c-30953dd71a5f.png)

> JobRepository : 작업열을 위한 저장소
> UserRedisTemplate : 큐에 들어간 인원을 위한 Strings 자료 구조 Template, TTL 설정 및 현재 큐에 있는지 확인 용도
> JobRedisTemplate : 작업열을 위한 Set 자료 구조 Template, 큐에 들어간 인원의 사이즈 측정 용도

> WaitQueueRepository : 대기열을 위한 저장소
> UserRedisTemplate : 큐에 들어간 인원을 위한 Strings 자료 구조 Template, TTL 설정 및 현재 큐에 있는지 확인 용도
> WaitQueueRedisTemplate : 대기열을 위한 SortedSet 자료 구조 Template, 큐에 들어간 인원의 사이즈 측정 및 랭킹 측정 용도

- 작업에 관한것은 JobService가 담당하고 대기열이 필요한 경우 대기열 서비스(WaitQueuService) 를 이용하도록 관점을 변경
- 대기열/작업열 진입/퇴출 작업이 유저 추가/삭제 작업과 동반되어야 하므로, user 자료구조와 queue자료 구조를 같은 repository에 배치

## 2. 대기열(SortedSet)과 작업열(Set)의 Key에 대한 TTL 제거
- 특정 시간에 스케쥴러로 이벤트가 끝난 Key 일괄 제거 예정

## 3. 이벤트에서 설정한 (작업열 크기, 작업열 유저 TTL) 을 이용한 예상 시간 계산
- 한명당 작업 예상 시간 = 작업열 유저 TTL / 작업열 크기
- 대기열 예상 시간 = 대기열 랭킹 * 한명당 작업 예상 시간

## 의문점
변경된 구조  `대기열/작업열 진입/퇴출 작업이 유저 추가/삭제 작업과 동반되어야 하므로, user 자료구조와 queue자료 구조를 같은 repository에 배치`
위와 같이 변경 할시 하나의 repository 에 여러개의 자료구조가 포함되니, 올바른 구조인지 의문이 듭니다.

**Comment by wheejuni** [comment]
코멘트가 늦어져 죄송합니다.
하나의 레포지토리에 여러개의 자료구조가 다뤄지는 것이 어색해 보이지는 않습니다.

"자료구조" 자체는 다양할 수 있지만, 제가 우려하는 것은 오히려 다양한 유즈 케이스들이 한 인터페이스에 섞이는 일입니다.
지금 명백하게 한 인터페이스에 두 개 이상의 비즈니스 로직이 담기게 되었으므로, 이 관점에서 설계 개선을 시도하셔도 좋을 듯합니다. 물론 지금 설계로도 좋습니다.
